---
# tasks file for jenkins
- name: using rehl file
  include_tasks: rehl.yml
  when: ansible_distribution == "RedHat"
 
- name: using centos file
  include_tasks: rehl.yml
  when: ansible_distribution == "CentOS"

- name: using ubuntu file
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: using fedora file
  include_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: using suse file
  include_tasks: suse.yml
  when: ansible_distribution == "SUSE"

