---
# tasks file for jenkins
- name: using rehl file
  include_tasks: rehl.yml
  when: ansible_distribution == "RedHat"
 
- name: using centos file
  include_tasks: rehl.yml
  when: ansible_distribution == "CentOS"


