- name: installing java
  yum:
    name: openjdk-8-jre-headless
    state: present

- name: add jenkins key
  apt_key:
    state: present
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

- name: add repo in sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: deb https://pkg.jenkins.io/debian-stable binary/


- name: install jenkins
  apt:
    name: jenkins
    state: present

- name: starting jenkins
  service:
    name: jenkins
    state: started
    enabled: yes

